name: dogapp
description: "A lost and found pet app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # Firebase for backend (replacing Supabase)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  

  flutter_dotenv: ^5.1.0
  # Remove or comment out Supabase
  supabase_flutter: ^2.8.2
  
  # HTTP requests
  http: ^1.2.2
  
  # State management
  provider: ^6.1.2
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # Location services
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Phone number formatting and validation
  intl_phone_field: ^3.2.0
  
  # Form validation
  form_field_validator: ^1.1.0
  
  # Shared preferences for local storage
  shared_preferences: ^2.3.2
  
  # Loading indicators
  flutter_spinkit: ^5.2.1
  
  # Toast messages
  fluttertoast: ^8.2.8
  
  # UUID generation
  uuid: ^4.5.1
  
  # Date formatting
  intl: ^0.19.0
  
  # Cards with swipe functionality (for the dating app style UI)
  flutter_card_swiper: ^7.0.1
  
  # Smooth page indicator
  smooth_page_indicator: ^1.2.0
  
  # Phone number validation (optional - for format checking)
  phone_numbers_parser: ^8.3.0

  # URL launcher for phone calls, emails, web links
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/dogapp_logo.png"

flutter:
  uses-material-design: true
  
  # Add your app assets here
  assets:
    - .env
    - assets/dogapp_logo.png

  
  # Add custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf